# -- 繁體中文 --
# 急速模式
# 直接讀取地圖文件, 不經過伺服器內部處理
# 1.14 以上的版本開始支持
# 防止礦物透視, 一樣能正常運行
# -- English --
# Fastest mode
# Read the map file directly, without internal processing by the server
# 1.14 and later supported
# Prevent XRAY, normal operation
fastest-mode: true



# -- 繁體中文 --
# 最高可擴展的視野距離
# 建議值,伺服器設置3-6,插件設置4-32 (最高能到32)
# 不影響伺服器本身的視野距離
# 實際上是依照客戶端的視野距離來調整,但如果客戶端條超過此限值,一樣只有此限制的視野距離
# 從此插件延伸的區塊不會載入實體/方塊更新
# -- English --
# Highest extendable field of view
# Recommended value, server setting 3-6, plug-in setting 4-32 (up to 32)
# Does not affect the field of view of the server itself
# The first level is adjusted according to the visual field distance of the client, but if the client bar exceeds this interval, there is only this limited visual field distance.
# The chunkchain extended from this plugin will not load entity / block updates
extend-view-distance: 32



# -- 繁體中文 --
# 每個tick能發送給全部玩家多少個區塊
# 過低時區塊則會很慢才給滿玩家
# 數值取決於網路速度和CPU性能來做調整
# 越高越好, 但過高可能會造成堵塞
# -- English --
# How many chunks can each tick send to players
# When it is too low, the chunk will be slow to fill the player
# The value depends on the network speed and CPU performance
# Higher is better, but too high may cause chunkage
player-tick-send-chunk-amount: 30



# -- 繁體中文 --
# 如果伺服器有 3 位玩家, player-tick-send-chunk-amount: 30, player-tick-send-chunk-amount-sole: 5
# 每個 tick 都會隨機抽選 30 次玩家, 每個玩家最多只能拿到 5 個區塊
# 最後因為限制, 總共只發送了 15 區塊 (3 * 15)
# 這是為了確保玩家不會因為發送區塊過太多而卡頓
# -- English --
# If the server has 3 player, player-tick-send-chunk-amount: 30, player-tick-send-chunk-amount-sole: 5
# Each tick will randomly select 30 players, each player can only get up to 5 chunks
# Finally, due to restrictions, only 15 chunks were sent in total (3 * 15)
# This is to ensure that players do not lag because they send too many chunks
player-tick-send-chunk-amount-sole: 5



# -- 繁體中文 --
# 由於插件發送的區塊晚於伺服器, 所以當 prevent-xray 啟用時, 發送的區塊都將會被處理
# 直到玩家靠近該區塊, 伺服器才會發送伺服器本身的區塊 (有辦法看見礦物, 或是經過 paper 特殊處理), 此時的區塊才看得件礦物
# 如果插件發送的區塊把伺服器的覆蓋了, 直到玩家離開區塊很遠 並再度靠近, 否則該區塊的礦物會完全看不見
# 如果察覺, 此插件提供的區塊, 會覆蓋到伺服器本身的區塊
# 或是中途缺少幾圈區塊
# 則調整此值
# 補正: server.properties -> view-distance + server-field-view-correction
# -- English --
# Since the chunk sent by the plugin is later than the server, when prevent-xray is enabled, the send chunk will be processed.
# Until the player approaches the chunk , the server will not send the chunk of the server itself (can see the ore, or special processing by paperSpigot).
# If the chunk sent by the plugin covers the server, until the player is far away from the chunk and be close to again, ore the minerals in the chunk will be completely invisible.
# If you notice that the chunk provided by this plugin will overwrite the chunk of the server itself.
# Or missing a few lap chunk halfway
# adjust this value
# Correction: server.properties -> view-distance + server-field-view-correction
server-field-view-correction: 1



# -- 繁體中文 --
# 每次切換世界都要等待一段時間才發送區塊
# 如果設置太少, 會造成客戶端顯示錯誤
# 建議數值 ((伺服器 view-distance * 伺服器 view-distance) * 2) + 100
# -- English --
# Every time you switch the world, you have to wait for a period of time before sending the chunks.
# If the setting is too small, it will cause the client to display errors
# Suggested value: ((Server view-distance * Server view-distance) * 2) + 100
delayed-send-tick: 100



# -- 繁體中文 --
# 防止礦物透視作弊
# 暴力替換, 不使用任何計算
# -- English --
# Prevent mineral perspective cheating
# Force replace, without using any calculations
prevent-xray:

  # -- 繁體中文 --
  # 是否啟用
  # -- English --
  # Whether to enable
  enable: true

  # -- 繁體中文 --
  # 轉換清單
  # -- English --
  # Conversion list
  conversion:
    STONE:
      - COAL_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - GOLD_ORE
      - IRON_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
    NETHERRACK:
      - NETHER_QUARTZ_ORE



# -- 繁體中文 --
# 世界黑名單
# 在此名單的世界不要提供視野距離擴展
# -- English --
# World Blacklist
# Don't provide visual range extension in the world of this list
world-blacklist:
  - world_nether



# -- 繁體中文 --
# 後臺調適模式
# 0 關閉
# 1 視圖
# 2 文字
# -- English --
# Background debug mode
# 0 Close
# 1 View
# 2 Text
background-debug-mode: 0